### PR TITLE
fix(account): ensure email exist in account

### PR DESCRIPTION
**Pull request by nafisholeh**
Email in `GoogleSignInAccount` object is always null. 

On Android, in case, we call `configure()` without email params (`accountName = null`), then we failed to fetch `accessTokens` from `getTokens()`. 
When `accountName` is null, [this line](https://github.com/ExodusMovement/google-signin/blob/nafis/ensure-email-exist-in-account/android/src/main/java/co/apptailor/googlesignin/Utils.java#L37:L37) (`acct.getEmail()`) will cause error, i.e. `name must not be empty: null`.

This fix will allow `configure()` called without email, but app still can get `accessToken` from `getTokens()`.

reference: [upstream repo](https://github.com/react-native-google-signin/google-signin/blob/master/android/src/main/java/com/reactnativegooglesignin/Utils.java#L65) and [official docs](https://developers.google.com/android/reference/com/google/android/gms/common/Scopes)

### CODE REVIEW

**Review by gutenye — APPROVED** [review]
utACK

**Review by andrejborstnik — CHANGES_REQUESTED** [review]
nACK

Automatically adding scopes is not the best practice - explicit passing in is desired & already possible, right? In case we still want to set it automatically we should only do it if `accountName` is not set

**Comment by gutenye** [comment]
Closed by https://github.com/ExodusMovement/exodus-mobile/pull/13255

**Comment by nafisholeh** [comment]
> nACK
> 
> Automatically adding scopes is not the best practice - explicit passing in is desired & already possible, right? In case we still want to set it automatically we should only do it if `accountName` is not set

makes sense to me.

**Pull request closed without merging**
